### ISSUE TITLE
1.9 Support

### ISSUE THREAD

**Issue by HeroCC** [md-5/iTag#17]
Right now when running on Spigot 1.9, I get this error, it doesn't happen in 1.8:

> [19:26:39 WARN]: Exception in thread "Craft Scheduler Thread - 8"
> [19:26:39 WARN]: org.apache.commons.lang.UnhandledException: Plugin BungeePortals v1.1 generated an exception while executing task 22
> at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
> at com.fuzzoland.BungeePortals.MetricsLite.postPlugin(MetricsLite.java:285)
> at com.fuzzoland.BungeePortals.MetricsLite.access$3(MetricsLite.java:278)
> at com.fuzzoland.BungeePortals.MetricsLite$1.run(MetricsLite.java:173)
> at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
> at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
> ... 3 more

I know you are hard at work with the 1.9 update, but an update for this plugin would be great!

**Comment by HeroCC** [comment]
Oops, may have posted the wrong trace...
